const mockReviews = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "Nulla ac eleifend turpis, sit amet rutrum libero.",
    "Vestibulum in metus vel sem efficitur varius.",
    "Sed fermentum justo in justo ultricies, sed mattis lorem scelerisque.",
    "Fusce et nulla sit amet leo euismod pharetra.",
    "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    "Duis non odio quis purus rhoncus luctus.",
    "Suspendisse potenti. Nunc tincidunt nisl a magna bibendum suscipit.",
    "Curabitur euismod eros at dolor lobortis, vel sagittis enim mattis.",
    "Praesent efficitur mauris at sem auctor, in finibus dui molestie.",
    "Vivamus sit amet purus eget leo tristique molestie.",
    "Integer id velit a est mollis tincidunt.",
    "Proin sit amet ipsum nec orci efficitur congue.",
    "Nam euismod erat eget tellus interdum, in ultrices lacus tempor.",
    "Aliquam erat volutpat. Morbi ac felis in nunc vehicula consectetur.",
    "Fusce malesuada, dui at lacinia scelerisque, justo est vestibulum nibh, eget tempus odio urna vel dui.",
    "Nunc id mi sodales, pharetra felis eu, tincidunt lorem.",
    "Phasellus vitae justo eget nisl dapibus vestibulum.",
    "In sed est vitae magna aliquet varius.",
    "Ut fermentum turpis nec ligula convallis, ac eleifend nulla tempor.",
    "Vivamus blandit, leo id venenatis fringilla, elit lorem viverra justo, vel sollicitudin eros odio at tortor.",
    "Donec a nunc lacinia, condimentum nulla ac, auctor ex.",
    "Fusce accumsan odio id ipsum sodales, a fringilla odio rhoncus.",
    "Sed ac quam in mi fermentum hendrerit.",
    "Phasellus congue ex vel nunc sodales, at posuere arcu bibendum.",
    "Aenean scelerisque lectus vel turpis vestibulum, vel bibendum odio convallis.",
    "In eget lectus at eros vestibulum varius vitae quis lorem.",
    "Pellentesque eleifend nisl non enim mattis, in iaculis enim pretium.",
    "Ut vitae felis a magna vehicula fringilla.",
    "Suspendisse sit amet lorem vel enim mollis auctor.",
    "Vivamus nec dolor nec nulla tristique maximus.",
    "Phasellus vitae est nec libero ultricies eleifend.",
    "Praesent eu orci non mauris luctus sagittis.",
    "Vestibulum aliquet justo nec vehicula fermentum.",
    "Cras sit amet eros sed enim rhoncus fermentum.",
    "Pellentesque ac mi eu eros tincidunt sollicitudin.",
    "Morbi vel lorem vestibulum, fermentum odio nec, interdum eros.",
    "Duis ut neque et nisi pharetra tristique.",
    "Aenean malesuada nunc sed felis posuere, eu tempor nisl fringilla.",
    "Aliquam eget ligula et felis auctor tristique.",
    "Integer tincidunt est id lectus aliquet convallis.",
    "Vivamus et dui quis ligula lobortis viverra vel vel elit.",
    "Nam tincidunt tortor vitae leo fermentum, non dignissim ex dapibus.",
    "Nullam consectetur sapien in purus convallis, in tempor elit consectetur.",
    "Maecenas commodo magna vitae purus molestie, non fermentum sem luctus.",
    "Fusce rutrum justo at leo fringilla, ac sodales sem efficitur.",
    "In volutpat tortor vel libero scelerisque, ut placerat est laoreet.",
    "Praesent consequat tortor a consectetur placerat.",
    "Donec dictum orci eget purus fringilla, at lobortis metus condimentum.",
    "Nunc sit amet lacus vel nulla tempor eleifend.",
    "Vestibulum nec est non eros tincidunt maximus ac a odio.",
    "Proin et tellus scelerisque, laoreet metus a, volutpat ipsum.",
    "Aliquam euismod justo vitae ex gravida, vitae vulputate lorem tincidunt.",
    "Curabitur hendrerit nisi ut risus auctor vehicula.",
    "Sed et purus nec justo laoreet iaculis.",
    "In id augue at nunc commodo egestas.",
    "Morbi ut justo nec lacus dignissim tristique.",
    "Proin eget felis vel nunc vehicula rhoncus.",
    "Suspendisse efficitur libero vitae ipsum eleifend, sed faucibus mi molestie.",
    "Donec dictum risus sed nunc consequat, ac lobortis metus suscipit.",
    "Quisque nec velit in neque faucibus blandit.",
    "Nunc euismod ex vitae nulla varius, non eleifend nisi gravida.",
    "Curabitur eget elit ac ligula posuere hendrerit.",
    "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    "Phasellus nec est at tortor vehicula laoreet.",
    "Integer id nisi vitae ipsum tincidunt finibus.",
    "Aenean sit amet dolor nec magna hendrerit placerat.",
    "Suspendisse eget felis a risus vulputate blandit.",
    "Nunc consequat metus ac neque molestie, a pharetra odio bibendum.",
    "Fusce eu nulla ut sapien accumsan dictum.",
    "Integer nec enim nec metus tristique rhoncus.",
    "Praesent sed eros nec lacus congue pellentesque id eu lorem.",
    "Curabitur sed libero id ipsum faucibus fermentum.",
    "Suspendisse ac sapien eu velit viverra gravida.",
    "Praesent vitae nunc id nisl lobortis maximus.",
    "Donec sit amet nisi eget quam pharetra placerat.",
    "Phasellus eget neque at risus ullamcorper dapibus.",
    "Morbi at felis eget libero consequat dapibus.",
    "Nunc eget nisl nec purus dignissim dictum.",
    "Sed consequat nisi at ultricies tincidunt.",
    "Maecenas fermentum quam ut quam scelerisque, nec vulputate est hendrerit.",
    "Fusce in magna id arcu ultricies mollis id vel odio.",
    "Phasellus ac lorem at est gravida egestas ut id nisi.",
    "Nam nec odio id libero cursus volutpat.",
    "Proin sit amet turpis vel risus faucibus tincidunt."
];

// Assuming the API returns an object with a 'reviews' key
const mockData = {
    reviews: mockReviews
};

export default mockData;
